# Huawei Ascend NPU Stress Test Configuration
hardware:
  type: "ascend"
  driver_version: "auto"
  cann_version: "auto"

stress:
  memory_bandwidth:
    enabled: true
    test_duration: 300  # seconds
    memory_size: "8GB"
    bandwidth_test: true
    latency_test: true

metrics:
  collection_interval: 1  # seconds
  npu_metrics:
    - utilization
    - memory_used
    - memory_total
    - temperature
    - power_draw
  system_metrics:
    - cpu_usage
    - memory_usage

reporting:
  output_dir: "/app/reports"
  format: ["json", "csv"]
  generate_plots: true
  save_logs: true 