# Huawei Ascend NPU Training Configuration
hardware:
  type: "ascend"
  driver_version: "auto"
  cann_version: "auto"

benchmarks:
  training:
    resnet50_mindspore:
      enabled: true
      batch_size: 32
      epochs: 10
      learning_rate: 0.001
      optimizer: "adam"
      dataset: "imagenet"
      mixed_precision: true

metrics:
  collection_interval: 1  # seconds
  npu_metrics:
    - utilization
    - memory_used
    - memory_total
    - temperature
    - power_draw
  system_metrics:
    - cpu_usage
    - memory_usage

reporting:
  output_dir: "/app/reports"
  format: ["json", "csv"]
  generate_plots: true
  save_logs: true 