name: Sync Aliyun

on:
  workflow_dispatch:
    inputs:
      src:
        description: ""
        required: true
        default: "shaowenchen/xpu-benchmark"
      dest:
        description: ""
        required: true
        default: "registry.cn-beijing.aliyuncs.com/opshub/shaowenchen-xpu-benchmark"
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Working
        run: |
          tags=$(docker run --rm quay.io/skopeo/stable:v1.13.0 list-tags docker://${{ inputs.src }} | jq -r '.Tags[]')

          for tag in $tags; do
            echo "Copying ${{ inputs.src }}:$tag -> ${{ inputs.dest }}:$tag"
            docker run --rm -v ~/.docker/config.json:/auth.json quay.io/skopeo/stable:v1.13.0 copy --multi-arch all \
              docker://${{ inputs.src }}:$tag \
              docker://${{ inputs.dest }}:$tag \
              --dest-authfile /auth.json \
              --insecure-policy \
              --src-tls-verify=false \
              --dest-tls-verify=false \
              --retry-times 1
          done